# Generated by Django 2.2.1 on 2019-08-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='areg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=9)),
                ('vtotal', models.CharField(max_length=10)),
                ('vname', models.CharField(max_length=40)),
                ('vage', models.CharField(max_length=40)),
                ('region', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('id_proof', models.CharField(max_length=30)),
                ('id_number', models.CharField(max_length=30)),
                ('vehical_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ureg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
