# Generated by Django 2.2.1 on 2019-08-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areg',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='areg',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='areg',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='areg',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='ureg',
            old_name='Name',
            new_name='uname',
        ),
    ]
