# Generated by Django 2.2.1 on 2019-08-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20190827_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='book_id',
        ),
    ]
