# Generated by Django 2.2.1 on 2019-08-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_booking_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ureg',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='region',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vname',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vage',
            field=models.CharField(max_length=30),
        ),
    ]
